data:
  dataset: "celeba"
  root: "./data/celeba-subset"
  from_hub: true  # use local folder data/celeba-subset
  repo_name: "electronickale/cmu-10799-celeba64-subset"
  image_size: 64
  channels: 3
  num_workers: 4
  pin_memory: true
  augment: true

# TODO: build your model architecture, feel free to add or exclude any of these options
model:
  base_channels: 128
  channel_mult: [1, 2, 2, 4]
  num_res_blocks: 2
  attention_resolutions: [16, 8]
  num_heads: 4
  dropout: 0.1
  use_scale_shift_norm: true

# TODO: your training hyperparameters, feel free to add or exclude any of these options
training:
  batch_size: 64
  learning_rate: 0.0002
  weight_decay: 0.0
  betas: [0.9, 0.999]
  ema_decay: 0.9999
  ema_start: 5000
  gradient_clip_norm: 1.0
  num_iterations: 100000
  log_every: 100
  sample_every: 5000
  save_every: 10000
  num_samples: 64

# TODO: your ddpm algorithm hyperparameters, feel free to add or exclude any of these options
ddpm:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  parameterization: "v"

sampling:
  num_steps: 1000
  sampler: "ddpm" # for the first hw we only need ddpm sampling, this is a placeholder where you can add more options yourself later

infrastructure:
  seed: 42
  device: "cuda"
  num_gpus: 1
  mixed_precision: true
  compile_model: false # only tested false

checkpoint:
  dir: "./checkpoints"
  resume: null

logging:
  dir: "./logs"
  wandb:
    enabled: true
    project: "cmu-10799-diffusion"
    entity: null
